#global variables
name: Matteo
title: Matteo Marinacci
description: "HELLO SITE"
# permalink: /about
email: "matteo.marinacci@gmail.com"
github: "https://github.com/MizuNoMashu"
site: "https://MizuNoMashu.github.io"

theme: minima